from keras import Model
from keras_reservoir_computing.layers.readouts.base import ReadOut


class ReservoirTrainer:
    def __init__(self, model: Model, readout_targets: dict):
        """
        Custom trainer for Read-Out layers, ensuring correct dependency order.

        This class is designed to handle the training of `ReadOut` layers within a Keras model.
        It ensures that the `ReadOut` layers are trained in the correct topological order,
        respecting the dependencies between them.

        Parameters
        ----------
        model : tf.keras.Model
            The Keras model containing `ReadOut` instances.
        readout_targets : dict
            Mapping of `ReadOut` layer names to their corresponding target tensors.

        Attributes
        ----------
        model : tf.keras.Model
            The Keras model containing `ReadOut` instances.
        readout_targets : dict
            Mapping of `ReadOut` layer names to their corresponding target tensors.
        readout_layers_list : list
            List of `ReadOut` layers in the model, sorted in topological order.
        intermediate_models : dict
            Dictionary mapping `ReadOut` layer names to their corresponding intermediate models.

        Notes
        -----
        - The `ReadOut` layers must be present in the model and their names must match the keys in `readout_targets`.
        - Intermediate models are created for each `ReadOut` layer to generate the necessary inputs for training.
        - This class assumes that the `ReadOut` layers are independent of each other, except for the order in which they are trained.
        """
        self.model = model
        self.readout_targets = readout_targets

        # Find all ReadOut layers in topological order
        # model.layers is already sorted in topological order
        self.readout_layers_list = [
            layer
            for layer in self.model.layers
            if isinstance(layer, ReadOut) and layer.name in self.readout_targets.keys()
        ]

        # Prepare intermediate models for each ReadOut layer
        self.intermediate_models = {}
        for readout_layer in self.readout_layers_list:
            self.intermediate_models[readout_layer.name] = Model(
                inputs=model.input, outputs=readout_layer.input
            )

    def fit_readout_layers(self, X):
        """
        Train all ReadOut layers in the correct order using intermediate models.

        This method iterates over the `ReadOut` layers in topological order and trains each one using the
        intermediate outputs generated by the corresponding intermediate model.

        Parameters
        ----------
        X : tf.Tensor
            The input data to generate intermediate outputs.

        Notes
        -----
        - The input data `X` should be compatible with the input shape of the model.
        - The method prints the progress of training each `ReadOut` layer.
        """
        print("\n=== Training ReadOut Layers in Topological Order ===")
        
        batch_size = X.shape[0]

        for readout_layer in self.readout_layers_list:

            # Get intermediate output for this ReadOut layer
            intermediate_model = self.intermediate_models[readout_layer.name]
            readout_input = intermediate_model.predict(X, batch_size=batch_size, verbose=0)

            # Get the expected target
            target = self.readout_targets[readout_layer.name]

            # Train ReadOut layer
            print(f"Fitting {readout_layer.name}...")
            readout_layer.fit(readout_input, target)

        print("All ReadOut layers fitted successfully.")


__all__ = ["ReservoirTrainer"]

def __dir__() -> list:
    return __all__