import logging
from typing import List, Union

import tensorflow as tf

from keras_reservoir_computing.layers.readouts.base import ReadOut

logger = logging.getLogger(__name__)


class ReservoirTrainer:
    def __init__(
        self, model: tf.keras.Model, readout_targets: dict, log: bool = False
    ) -> None:
        """
        Custom trainer for Read-Out layers, ensuring correct dependency order.

        This class is designed to handle the training of `ReadOut` layers within a Keras model.
        It ensures that the `ReadOut` layers are trained in the correct topological order,
        respecting the dependencies between them.

        Parameters
        ----------
        model : tf.keras.Model
            The Keras model containing `ReadOut` instances.
        readout_targets : dict
            Mapping of `ReadOut` layer names to their corresponding target tensors.
        log : bool, optional
            Whether to print logging information during training.

        Attributes
        ----------
        model : tf.keras.Model
            The Keras model containing `ReadOut` instances.
        readout_targets : dict
            Mapping of `ReadOut` layer names to their corresponding target tensors.
        readout_layers_list : list
            List of `ReadOut` layers in the model, sorted in topological order.
        _intermediate_models : dict
            Lazily created dictionary mapping `ReadOut` layer names to their intermediate models.

        Notes
        -----
        - The `ReadOut` layers must be present in the model and their names must match the keys in `readout_targets`.
        - Intermediate models are created lazily when needed for better performance.
        - This class assumes that the `ReadOut` layers are independent of each other, except for the order in which they are trained.
        """
        self.model = model
        self.readout_targets = readout_targets
        self.log = log
        
        if log:
            logging.basicConfig(level=logging.INFO)

        # Find all ReadOut layers in topological order
        # model.layers is already sorted in topological order
        # Only include layers that are in readout_targets
        self.readout_layers_list = [
            layer
            for layer in self.model.layers
            if isinstance(layer, ReadOut) and layer.name in self.readout_targets.keys()
        ]

        # Will be populated lazily when needed
        self._intermediate_models = {}

    def _get_intermediate_model(self, layer_name: str) -> tf.keras.Model:
        """
        Lazily create and return an intermediate model for the specified layer.

        Parameters
        ----------
        layer_name : str
            The name of the ReadOut layer to create an intermediate model for.

        Returns
        -------
        tf.keras.Model
            The intermediate model that outputs the inputs to the specified ReadOut layer.
        """
        if layer_name not in self._intermediate_models:
            layer = next(
                layer_obj
                for layer_obj in self.readout_layers_list
                if layer_obj.name == layer_name
            )
            self._intermediate_models[layer_name] = tf.keras.Model(
                inputs=self.model.input, outputs=layer.input
            )
        return self._intermediate_models[layer_name]

    @staticmethod
    @tf.function(jit_compile=True)
    def _warm_forward(model, warmup, data):
        model(warmup, training=False)  # warm-up
        return model(data, training=False)


    def fit_readout_layers(
        self,
        warmup_data: Union[tf.Tensor, List[tf.Tensor]],
        input_data: Union[tf.Tensor, List[tf.Tensor]],
    ) -> None:
        """
        Train all ReadOut layers in the correct order using intermediate models.

        This method iterates over the `ReadOut` layers in topological order and trains each one using the
        intermediate outputs generated by the corresponding intermediate model.

        Parameters
        ----------
        warmup_data : tf.Tensor or List[tf.Tensor]
            The input data to warm up the model before training the ReadOut layers.

        input_data : tf.Tensor or List[tf.Tensor]
            The input data to generate intermediate outputs.

        Notes
        -----
        - The input data `input_data` should be compatible with the input shape of the model.
        - The method prints the progress of training each `ReadOut` layer.
        """
        if self.log:
            logger.info("\n=== Training ReadOut Layers in Topological Order ===")


        # Optimize for memory utilization by clearing intermediate results after each layer is trained
        for readout_layer in self.readout_layers_list:
            layer_name = readout_layer.name

            if self.log:
                logger.info(f"Processing {layer_name}...")

            # Get intermediate model for this layer (created lazily)
            intermediate_model = self._get_intermediate_model(layer_name)

            # Warm up and get the intermediate inputs
            if self.log:
                logger.info(f"  Warming up and getting intermediate inputs for model {layer_name}...")
            readout_input = self._warm_forward(
                intermediate_model, warmup_data, input_data
            )

            # Get the expected target
            target = self.readout_targets[layer_name]

            # Train ReadOut layer
            if self.log:
                logger.info(f"  Fitting {layer_name}...")
            readout_layer.fit(readout_input, target)

            # Clear the intermediate output to free memory
            readout_input = None

            # If this is the last layer using this intermediate model, we can remove it
            del self._intermediate_models[layer_name]

            if self.log:
                logger.info(f"  {layer_name} fitted successfully.")

        if self.log:
            logger.info("All ReadOut layers fitted successfully.")
